"""external requests table

Revision ID: 1eff4f0150fc
Revises: 8bc2ea5553d7
Create Date: 2026-06-04 11:52:19.669318
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1eff4f0150fc'
down_revision: Union[str, None] = '8bc2ea5553d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('quoted_price', sa.Integer(), nullable=False),
    sa.Column('guest_mailbox', sa.String(length=255), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('owner_phone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=12), nullable=False),
    sa.Column('whatsapp_sent', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_requests_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_requests_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_requests_token'), ['token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_requests_token'))
        batch_op.drop_index(batch_op.f('ix_external_requests_status'))
        batch_op.drop_index(batch_op.f('ix_external_requests_customer_id'))
        batch_op.drop_index(batch_op.f('ix_external_requests_asset_id'))

    op.drop_table('external_requests')
    # ### end Alembic commands ###
