"""booking reminder flag

Revision ID: 3c6ce3939eac
Revises: 7b61716f71e9
Create Date: 2026-06-05 23:50:31.850797
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3c6ce3939eac'
down_revision: Union[str, None] = '7b61716f71e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent')

    # ### end Alembic commands ###
