"""transfer zones

Revision ID: 4a58db4d9d04
Revises: a01028b89873
Create Date: 2026-06-03 14:30:06.260047
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4a58db4d9d04'
down_revision: Union[str, None] = 'a01028b89873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('car_price', sa.Float(), nullable=False),
    sa.Column('van_price', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_zones')
    # ### end Alembic commands ###
