"""booking payment fields

Revision ID: 79cfed0c08b3
Revises: 1eff4f0150fc
Create Date: 2026-06-04 19:18:06.084369
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '79cfed0c08b3'
down_revision: Union[str, None] = '1eff4f0150fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False, server_default='unpaid'))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('stripe_payment_intent', sa.String(length=255), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_bookings_payment_status'), ['payment_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_payment_status'))
        batch_op.drop_column('stripe_payment_intent')
        batch_op.drop_column('stripe_session_id')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
