"""app settings table

Revision ID: 7b61716f71e9
Revises: 79cfed0c08b3
Create Date: 2026-06-05 23:30:22.431061
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7b61716f71e9'
down_revision: Union[str, None] = '79cfed0c08b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
