"""mailboxes table

Revision ID: 9478a6fbb5c2
Revises: 4a58db4d9d04
Create Date: 2026-06-04 03:33:47.767326
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9478a6fbb5c2'
down_revision: Union[str, None] = '4a58db4d9d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailboxes')
    # ### end Alembic commands ###
