"""packages and percent deposit

Revision ID: a01028b89873
Revises: de0246b41c85
Create Date: 2026-06-03 04:04:09.884292
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a01028b89873'
down_revision: Union[str, None] = 'de0246b41c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('guided', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rental_packages_asset_id'), ['asset_id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_percent', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('show_license_to_customer', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('package_name', sa.String(length=64), nullable=False, server_default=''))
        batch_op.create_foreign_key('fk_bookings_package_id', 'rental_packages', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_package_id', type_='foreignkey')
        batch_op.drop_column('package_name')
        batch_op.drop_column('package_id')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('show_license_to_customer')
        batch_op.drop_column('deposit_percent')

    with op.batch_alter_table('rental_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_packages_asset_id'))

    op.drop_table('rental_packages')
    # ### end Alembic commands ###
